### ISSUE TITLE
Got status code 405 from service at path /series/{id}/episodes/query

### ISSUE THREAD

**Issue by AntonySalas** [adrenth/thetvdb2#9]
Hi.

Show error when execute:

`var_dump($client->series()->getEpisodesWithQuery(267440,['airedEpisodeNumber'=>8])->getAttributes());`

Method not allowed.

it only works with `['airedSeason'=>1] `param.
and with param `['airedSeason'=>1,'airedEpisodeNumber '=>8]`, only get by 'airedSeason'

**Comment by adrenth** [comment]
Thanks for sharing.

Since the `$query` parameter can contain an array with a lot of parameters in different combination  it is not the responsibility of this package to do validation of the input.

It seems that `airedSeason` parameter is required when you provide `airedEpisodeNumber`. Which seems logical to me. Make sure to add this logic to your code before running the method `getEpisodesWithQuery`.

**Comment by AntonySalas** [comment]
using `['airedSeason'=>1,'airedEpisodeNumber '=>8]`, return all episodes of this season.

I think I should just get back data from the requested chapter.
